name: Test kubeconfig
# Run go test when commits are pushed to any branch 
#  or there's a pull request to main

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test_kubeconfig:
    runs-on: ubuntu-latest

    steps:
        name: nodes
      - uses: danielr1996/kubectl-action@1.0.0
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: get nodes

      # - name: Install Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.16.4
