name: Run tests
# Run go test when commits are pushed to any branch 
#  or there's a pull request to main

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  test_package:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch required Go modules
        run:  go mod download

      - name: Build
        run:  go build -v ./...

      - name: Run functional tests
        run:  go test -v ./...
