name: Test, Build and Push
# This will run when a tag is pushed 
# It will only build and push to the DockerHub if the branch is main

on:
  push:
    tags:
      - 'v*'

jobs:
  test_package:
    runs-on: ubuntu-latest

    steps:
        
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch required Go modules
        run:  go mod download

      - name: Build
        run:  go build -v ./...

      - name: Run functional tests
        run:  go test -v ./...

  build_docker_image:
    needs: test_package
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dpgraham4401/dpgraham
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  deploy_new_image:
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dpgraham4401/dpgraham

      - uses: danielr1996/kubectl-action@1.0.0
      name: test_kube
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: set image -n dpgraham deployments.apps/dpgraham dpgraham=dpgraham4401/dpgraham:${{ steps.meta.outputs.tags }}

